# Generated by Django 5.2.3 on 2025-07-29 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_category_options_rating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingimages',
            old_name='image',
            new_name='after',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='apps.work'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratingimages',
            name='before',
            field=models.ImageField(blank=True, null=True, upload_to='rating_images'),
        ),
    ]
